### ISSUE TITLE
IP2Location geolocation web service

### ISSUE THREAD

**Issue by ip2location** [rednaks/django-ip-geolocation#7]
Would you be considered to add another geolocation service - IP2Location web service into this project? If yes, you can sign up for a trial account at https://www.ip2location.com/web-service/ip2location for development. If you need any assistance, please let us know.

**Comment by rednaks** [comment]
Hi, thank you for your interest, I'll look into it and see how it can be done :)

**Comment by rednaks** [comment]
@ip2location just merged the integration with IP2location ws, it should be released soon :)
